sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - composer install --no-interaction --prefer-source --dev

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: false
